### ISSUE TITLE
https://grepbugs.com/ not accessible

### ISSUE THREAD

**Issue by chcg** [foospidy/GrepBugsPluginNotepadPlusPlus#3]
Just a application error page is displayed with:

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

@foospidy Could you please check that.

**Comment by chcg** [comment]
Fixed the plugin download by using the github release, see https://github.com/notepad-plus-plus/nppPluginList/commit/64c73bd3624fbe83556873091bb252aa00a9ef85
What about a release with the x64 version of the plugin?

**Comment by foospidy** [comment]
@chcg The site is hosted on a Heroku free dyno, which has limited runtime hours per month. Unfortunately, the limit was reached for October. However, it should reset on Nov 1. I realize this is not the best situation, my apologies for the inconvenience.

Thanks for updating the plugin download on the nppPluginList. That may be a better option going forward. However, there would still be issues with the plugin being able to download the ruleset.

**Comment by chcg** [comment]
@foospidy Ok. At least the download of the plugin itself should work now without problems.

What about a release with the x64 version of the plugin? Also the ANYCPU version should work independently of 32\64 bit due to the connection to native dllexport interface it is necessary to have 2 plugin versions to support N++ for 32 and 64 bit.

**Comment by foospidy** [comment]
The site should be available now :)

Regarding a x64 version. Unfortunately I don't have the time/resources to work on that. The best I can suggest right now is to create an enhancement request ticket with the "help wanted" label. Perhaps there my be folks in the Notepad++ community that would be willing to contribute.

**Comment by foospidy** [comment]
Created issue/request here https://github.com/foospidy/GrepBugsPluginNotepadPlusPlus/issues/4
